{"name": "Тест: Проверка перехода в историю заказов", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <tests.test_personal_account.TestsPersonalAccount object at 0x00000177CC7A4ED0>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"f2b78687-ee24-406e-8d3e-abf7c322dd03\")>\nuser = {'email': 'updjvoq@example.com', 'json': {'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmIz...': True, 'user': {'email': 'updjvoq@example.com', 'name': 'aopwniwr'}}, 'name': 'aopwniwr', 'password': 'jdkgmwslmhad'}\n\n    @allure.title('Тест: Проверка перехода в историю заказов')\n    @allure.description('Проверяет, что пользователь может перейти в историю заказов после авторизации в личном кабинете.')\n    def test_navigate_to_order_history(self, driver, user):\n        personal_account_page = PersonalAccountPage(driver)\n        personal_account_page.navigate_to_url(Urls.LOGIN)\n        personal_account_page.login_account(user)\n        personal_account_page.go_to_personal_account()\n>       personal_account_page.go_to_order_history()\n\ntests\\test_personal_account.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\personal_account_page.py:26: in go_to_order_history\n    list_history = self.wait_for_element_visible(PersonalAccountLocators.ORDER_HISTORY)\npages\\base_page.py:15: in wait_for_element_visible\n    return WebDriverWait(self.driver, 10).until(ec.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"f2b78687-ee24-406e-8d3e-abf7c322dd03\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x00000177CC7D6160>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "description": "Проверяет, что пользователь может перейти в историю заказов после авторизации в личном кабинете.", "steps": [{"name": "Авторизация", "status": "passed", "parameters": [{"name": "data", "value": "{'email': 'updjvoq@example.com', 'name': 'aopwniwr', 'password': 'jdkgmwslmhad', 'json': {'success': True, 'user': {'email': 'updjvoq@example.com', 'name': 'aopwniwr'}, 'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmIzMTZlOWVkMjgwMDAxYjQzYmE2OCIsImlhdCI6MTcxODMwMTAzOCwiZXhwIjoxNzE4MzAyMjM4fQ._bkimUDFXRk60H9iLDub_ia7G8wfBRmk7fC0fWTX-8E', 'refreshToken': 'ec7899609fcc32a57a1270ba8b7dfc9d0233075c8edfea10b40aac124f8967c3c864d63f2a5ff2ff'}}"}], "start": 1718301039238, "stop": 1718301039360}, {"name": "Нажимаем на кнопку Личный кабинет", "status": "passed", "start": 1718301039360, "stop": 1718301039595}, {"name": "Переходим в историю", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\coroniola\\Downloads\\D1\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\coroniola\\Downloads\\D1\\Diplom_3\\pages\\personal_account_page.py\", line 26, in go_to_order_history\n    list_history = self.wait_for_element_visible(PersonalAccountLocators.ORDER_HISTORY)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\coroniola\\Downloads\\D1\\Diplom_3\\pages\\base_page.py\", line 15, in wait_for_element_visible\n    return WebDriverWait(self.driver, 10).until(ec.visibility_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\coroniola\\Downloads\\D1\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1718301039595, "stop": 1718301050112}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1718301038465, "stop": 1718301050115, "uuid": "8a3a97b7-42c7-4a4b-8b48-5c06e9cefad8", "historyId": "0735a930818194c81e1d37d00f979134", "testCaseId": "b5516c131ec71887db42ec216cdfa5c0", "fullName": "tests.test_personal_account.TestsPersonalAccount#test_navigate_to_order_history", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_personal_account"}, {"name": "subSuite", "value": "TestsPersonalAccount"}, {"name": "host", "value": "WIN-FL5IV5LS9IV"}, {"name": "thread", "value": "19436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_personal_account"}]}